### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by dawngerpony** [duffj/eventbot-web-api#1]
I need to convert the app to use Unicode.

```2017-02-09T21:59:34.489693+00:00 app[web.1]: Traceback (most recent call last):
2017-02-09T21:59:34.489691+00:00 app[web.1]: [2017-02-09 21:59:34,489] ERROR in app: Exception on /webhook/application_form [POST]
2017-02-09T21:59:34.489693+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
2017-02-09T21:59:34.489694+00:00 app[web.1]:     response = self.full_dispatch_request()
2017-02-09T21:59:34.489695+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
2017-02-09T21:59:34.489695+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2017-02-09T21:59:34.489696+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
2017-02-09T21:59:34.489713+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
2017-02-09T21:59:34.489697+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-02-09T21:59:34.489714+00:00 app[web.1]:     rv = self.dispatch_request()
2017-02-09T21:59:34.489716+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2017-02-09T21:59:34.489715+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
2017-02-09T21:59:34.489717+00:00 app[web.1]:   File "/app/eventbot/bot.py", line 37, in web_hook_application_form
2017-02-09T21:59:34.489717+00:00 app[web.1]:     slack.post_form_to_webhook(form)
2017-02-09T21:59:34.489718+00:00 app[web.1]:   File "/app/eventbot/integrations/slack.py", line 15, in post_form_to_webhook
2017-02-09T21:59:34.489719+00:00 app[web.1]:     """.format(**d)
2017-02-09T21:59:34.489720+00:00 app[web.1]: UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 241: ordinal not in range(128)
2017-02-09T21:59:34.489808+00:00 app[web.1]: [2017-02-09 21:59:34,489] app.py:1587 -        log_exception() [ERROR] Exception on /webhook/application_form [POST]
2017-02-09T21:59:34.489809+00:00 app[web.1]: Traceback (most recent call last):
2017-02-09T21:59:34.489811+00:00 app[web.1]:     response = self.full_dispatch_request()
2017-02-09T21:59:34.489810+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
2017-02-09T21:59:34.489811+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
2017-02-09T21:59:34.489812+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2017-02-09T21:59:34.489813+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
2017-02-09T21:59:34.489814+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-02-09T21:59:34.489814+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
2017-02-09T21:59:34.489815+00:00 app[web.1]:     rv = self.dispatch_request()
2017-02-09T21:59:34.489815+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
2017-02-09T21:59:34.489816+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2017-02-09T21:59:34.489818+00:00 app[web.1]:   File "/app/eventbot/integrations/slack.py", line 15, in post_form_to_webhook
2017-02-09T21:59:34.489817+00:00 app[web.1]:     slack.post_form_to_webhook(form)
2017-02-09T21:59:34.489817+00:00 app[web.1]:   File "/app/eventbot/bot.py", line 37, in web_hook_application_form
2017-02-09T21:59:34.489819+00:00 app[web.1]:     """.format(**d)
2017-02-09T21:59:34.489819+00:00 app[web.1]: UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 241: ordinal not in range(128)```

**Comment by dawngerpony** [comment]
All looks good now 👍
